global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: telegram

receivers:
  - name: telegram
    webhook_configs:
      - url: 'https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage'
        send_resolved: true
        http_config:
          follow_redirects: true
        max_alerts: 10

templates: []
